{\rtf1\ansi\ansicpg932\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red220\green220\blue220;\red41\green53\blue57;}
{\*\expandedcolortbl;;\cssrgb\c89020\c89020\c89020;\cssrgb\c21176\c27059\c28627;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs25\fsmilli12800 \cf2 \cb3 \expnd0\expndtw0\kerning0
[build]\
publish = "public"\
command = "hugo --theme=dimension --buildDrafts --gc --minify"}