{\rtf1\ansi\ansicpg932\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red67\green67\blue67;\red21\green23\blue26;\red172\green117\blue53;
}
{\*\expandedcolortbl;;\cssrgb\c33333\c33333\c33333;\cssrgb\c10588\c12157\c13725\c5098;\cssrgb\c73333\c53333\c26667;
}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
[build]\
publish = \cf4 "public"\cf2 \
command = \cf4 "hugo --gc --minify"\cf2 \
\
[context.production.environment]\
HUGO_VERSION = \cf4 "0.85.0"\cf2 \
HUGO_ENV = \cf4 "production"\cf2 \
HUGO_ENABLEGITINFO = \cf4 "true"\cf2 \
\
[context.split1]\
command = \cf4 "hugo --gc --minify --enableGitInfo"\cf2 \
\
[context.split1.environment]\
HUGO_VERSION = \cf4 "0.85.0"\cf2 \
HUGO_ENV = \cf4 "production"\cf2 \
\
[context.deploy-preview]\
command = \cf4 "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"\cf2 \
\
[context.deploy-preview.environment]\
HUGO_VERSION = \cf4 "0.85.0"\cf2 \
\
[context.branch-deploy]\
command = \cf4 "hugo --gc --minify -b $DEPLOY_PRIME_URL"\cf2 \
\
[context.branch-deploy.environment]\
HUGO_VERSION = \cf4 "0.85.0"\cf2 \
\
[context.next.environment]\
HUGO_ENABLEGITINFO = \cf4 "true"\cf2 \
}